### ISSUE TITLE
Maintain release changelog?

### ISSUE THREAD

**Issue by Daenyth** [lendup/fs2-blobstore#22]
It would be really helpful for making sure that updates are safe if you had a changelog in the project. Either with github release tags or a file in the repo.

**Comment by rolandomanrique** [comment]
@Daenyth I want to start a release now with version 0.2.x since we are moving to fs2 1.0.0-M5, I'll add a `CHANGELOG` file in the root of the project and start by tagging latest 0.1.7 release in github.

Thanks for the help with all these issues.

**Comment by rolandomanrique** [comment]
@Daenyth is this [CHANGELOG](https://github.com/lendup/fs2-blobstore/blob/master/CHANGELOG.md) good to close this?

**Comment by Daenyth** [comment]
looks good!
